repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.33.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md|mdx)$

  - repo: local
    hooks:
      - id: typescript-typecheck
        name: TypeScript typecheck
        entry: npx tsc --noEmit
        language: system
        files: \.(ts|tsx)$
