repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.7.2
    hooks:
      - id: conventional-commits

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md)$
        additional_dependencies:
          - prettier@3.6.2
          - prettier-plugin-tailwindcss@0.6.14

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.33.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]

  - repo: local
    hooks:
      - id: typescript-typecheck
        name: TypeScript typecheck
        entry: npx tsc --noEmit
        language: system
        files: \.(ts|tsx)$
        exclude: src/components/**/*.tsx
